### ISSUE TITLE
Unable to create new account

### ISSUE THREAD

**Issue by BeyondSpace609520** [deptagency/algomart#60]
## Overview

![image](https://user-images.githubusercontent.com/56730274/140841556-648dba69-b49c-4dd6-be13-19f2a1a83f6e.png)

## To reproduce

```
[1636418886593] ERROR (185 on 643993e0280a): Bad Request
    context: "AlgorandAdapter"
    err: {
      "type": "Error",
      "message": "Bad Request",
      "stack":
          Error: Bad Request
              at Request.callback (/app/node_modules/superagent/src/node/index.js:879:15)
              at fn (/app/node_modules/superagent/src/node/index.js:1130:18)
              at IncomingMessage.<anonymous> (/app/node_modules/superagent/src/node/parsers/json.js:19:7)
              at IncomingMessage.emit (node:events:402:35)
              at endReadableNT (node:internal/streams/readable:1343:12)
              at processTicksAndRejections (node:internal/process/task_queues:83:21)
      "status": 400,
      "response": {
        "req": {
          "method": "POST",
          "url": "http://3.134.119.141:4001/v2/transactions",
          "data": {
            "type": "Buffer",
            "data": [
              130,
              163,
              ...
	      ...
              114,
              101,
              103
            ]
          },
          "headers": {
            "x-algo-api-token": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "content-type": "application/x-binary"
          }
        },
        "header": {
          "access-control-allow-origin": "*",
          "content-type": "application/json; charset=UTF-8",
          "vary": "Origin",
          "date": "Tue, 09 Nov 2021 00:48:06 GMT",
          "content-length": "714",
          "connection": "close"
        },
        "status": 400,
        "text": "{\"message\":\"TransactionPool.Remember: transaction OHLE3O3U2FAO6MO3V3CEVDLGDU3BLWTHUUI6V4MY2WZOE47DILMA: overspend (account A473OSLPGV7FEMMQ3VCAOX7PZNO44Y5X5VZQC34IJFL6LBHC2AMHCKH2CE, 
        data {_struct:{} Status:Offline MicroAlgos:{Raw:0} RewardsBase:0 RewardedMicroAlgos:{Raw:0} VoteID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 
        SelectionID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 
        VoteFirstValid:0 VoteLastValid:0 VoteKeyDilution:0 AssetParams:map[] Assets:map[] AuthAddr:AAAAAAAAA                                                       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ 
        AppLocalStates:map[] AppParams:map[] 
        TotalAppSchema:{_struct:{} NumUint:0 NumByteSlice:0} TotalExtraAppPages:0}, tried to spend {100                                                       0})\"}\n"
      }
    }
```

## Expected behavior

I don't have any idea what error text means.

**Comment by BeyondSpace609520** [comment]
I have testnet wallet address created by algod sandbox - `A473OSLPGV7FEMMQ3VCAOX7PZNO44Y5X5VZQC34IJFL6LBHC2AMHCKH2CE`,  I already funded there, but it still looks insufficient transaction.

![image](https://user-images.githubusercontent.com/56730274/140842210-dfb553f4-2f83-42d0-9bb7-144f3f462390.png)

**Comment by BeyondSpace609520** [comment]
Resolved issue myself, my test wallet is created by local node, not sync with testnet.
